# https://goreleaser.com/quick-start/
project_name: gorc
before:
  hooks:
    - go mod download
builds:
  - binary: gorc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
release:
  draft: true
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
      - README*
      - examples/*
